"""
RetailPulse Model Loader

Centralized loading of trained ML models.

All models are treated as read-only artifacts
generated by the completed notebook pipeline.
"""

from pathlib import Path

import joblib
import streamlit as st


PROJECT_ROOT = Path(__file__).resolve().parents[2]
MODEL_DIR = PROJECT_ROOT / "models"


@st.cache_resource
def load_forecasting_model():
    """Load the trained forecasting model."""
    return joblib.load(MODEL_DIR / "best_forecasting_model.pkl")


@st.cache_resource
def load_kmeans_model():
    """Load the trained K-Means model."""
    return joblib.load(MODEL_DIR / "kmeans_model.pkl")


@st.cache_resource
def load_scaler():
    """Load the segmentation scaler."""
    return joblib.load(MODEL_DIR / "scaler.pkl")


@st.cache_resource
def load_churn_model():
    """
    Load the primary churn model.

    Uses customer_churn_model.pkl as the project's
    primary churn model.
    """
    return joblib.load(MODEL_DIR / "customer_churn_model.pkl")