"""
RetailPulse Model Loader
========================

Centralized loading of trained ML models.

All models are treated as read-only artifacts
generated by the completed notebook pipeline.
"""

from __future__ import annotations

from pathlib import Path

import joblib
import streamlit as st

# ==========================================================
# Project Paths
# ==========================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]

MODEL_DIR = PROJECT_ROOT / "models"


# ==========================================================
# Generic Model Loader
# ==========================================================

@st.cache_resource(show_spinner=False)
def _load_model(model_name: str):
    """
    Generic model loader with validation.
    """

    model_path = MODEL_DIR / model_name

    if not model_path.exists():

        st.error(
            f"Model not found:\n{model_path}"
        )

        st.stop()

    try:

        return joblib.load(model_path)

    except Exception as e:

        st.error(
            f"Unable to load model:\n\n{e}"
        )

        st.stop()


# ==========================================================
# Forecasting Model
# ==========================================================

@st.cache_resource(show_spinner=False)
def load_forecasting_model():
    """
    Load best forecasting model.
    """

    return _load_model(
        "best_forecasting_model.pkl"
    )


# ==========================================================
# KMeans Model
# ==========================================================

@st.cache_resource(show_spinner=False)
def load_kmeans_model():
    """
    Load KMeans model.
    """

    return _load_model(
        "kmeans_model.pkl"
    )
# ==========================================================
# Scaler
# ==========================================================

@st.cache_resource(show_spinner=False)
def load_scaler():
    """
    Load the feature scaler used for customer segmentation.
    """

    return _load_model(
        "scaler.pkl"
    )


# ==========================================================
# Churn Model
# ==========================================================

@st.cache_resource(show_spinner=False)
def load_churn_model():
    """
    Load the primary customer churn model.
    """

    return _load_model(
        "customer_churn_model.pkl"
    )


# ==========================================================
# Load All Models
# ==========================================================

@st.cache_resource(show_spinner=False)
def load_all_models():
    """
    Load all production models at once.

    Returns
    -------
    dict
        Dictionary containing all loaded models.
    """

    return {

        "forecasting": load_forecasting_model(),

        "kmeans": load_kmeans_model(),

        "scaler": load_scaler(),

        "churn": load_churn_model(),

    }


# ==========================================================
# Export Functions
# ==========================================================

__all__ = [

    "load_forecasting_model",

    "load_kmeans_model",

    "load_scaler",

    "load_churn_model",

    "load_all_models",

]
